version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host  # 🔥 permite que el contenedor acceda a localhost del host  
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: uvicorn src.ollama_app:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host  # 🔥 permite que el contenedor acceda a localhost del host
    ports:
      - "8501:8501"
    volumes:
      - .:/code
    command: streamlit run src/app_streamlit.py --server.address 0.0.0.0 --server.port 8501
    depends_on:
      - web
